### ISSUE TITLE
Error types

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/Cofoundry.Plugins.ErrorLogging#1]
Hi,
Can this plugin register warnings and info events or only errors?

Thanks

**Comment by HeyJoel** [comment]
No, this is only for simple exception handling not logging. ASP.NET core provides an extensive [logging framework](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2), which you can hook into with the built in providers or 3rd party tools
